### ISSUE TITLE
Variants not found using multi-word search

### ISSUE THREAD

**Issue by mattsolo1** [macarthur-lab/gnomadjs#134] opened 2018-07-19 19:57 UTC
E.g. searching for `splice acceptor` or `5'` yields no variants.

![image](https://user-images.githubusercontent.com/8867295/42966718-18f23538-8b6c-11e8-8a16-d857935c0d7b.png)

**Comment by nawatts** [comment] 2018-07-19 19:58
Duplicate of #45. The problem is it's searching based on the actual value of the consequence field instead of what's displayed in the table.

https://github.com/macarthur-lab/gnomadjs/blob/6009d9a4a205c8a8a4ad29c4f0635e109e902402/packages/table/src/Table.js#L217-L239

**Comment by mattsolo1** [comment] 2018-07-19 20:36
Yeah, I guess since removing redux search it fails in more cases (before it was just `5' UTR` variants), but the cause is the same.

**Closed** 2018-07-19 20:48 UTC
